### ISSUE TITLE
Consider implementing forecast method for NARX model

### ISSUE THREAD

**Issue by jxx123** [jxx123/fireTS#1]
Implement a forecast method that is doing the following:

Given X(0), ... , X(t) and Y(0), ..., Y(t), output the forecast values of Y as a vector Y_hat(t+1), Y_hat(t+2), ... ,Y_hat(t+k).

**Comment by jjneojiajun** [comment]
any update on this? :)

**Comment by jxx123** [comment]
Thanks for your interests. I haven't started yet. Will let you know once I roll this out. Feel free to fork the repo in the mean time :)

**Comment by jxx123** [comment]
Just let you all know that the forecast feature is added. Thanks!
