### ISSUE TITLE
Paper link is broken

### ISSUE THREAD

**Issue by kusumy** [jxx123/fireTS#11]
Hi, 
I want to access the paper mentioned on this repository, but it seems the link is broken.

Regards

**Comment by jxx123** [comment]
The link is good to me. This is the paper title: Xie, Jinyu, and Qian Wang. "Benchmark Machine Learning Approaches with Classical Time Series Approaches on the Blood Glucose Level Prediction Challenge." KHD@ IJCAI. 2018. This is the link http://ceur-ws.org/Vol-2148/paper16.pdf If you still cannot get access to the paper, I will send you a pdf. Thanks.
