### ISSUE TITLE
correction to model.NARX.forecast method

### ISSUE THREAD

**Issue by danielkentwood** [jxx123/fireTS#8]
Line 135 in the forecast method of models.py has this: `deque(X[(-1 - d):(-1 - q):-1, i])`

I believe the middle slice is missing a term; it should be `deque(X[(-1 - d):(-1 - d - q):-1, i])`, otherwise if the exogenous regressor(s) are given a delay that is >= the exog_order, this will return an empty deque and the forecast method will fail.

**Comment by jxx123** [comment]
Oops, that's a good catch! Thanks a lot! I will fix this soon. If you want to fix it, feel free to send me a PR :)
